-- AlterTable
ALTER TABLE `Ingredient` ADD COLUMN `type` ENUM('INGREDIENT', 'PACKAGING_MATERIAL', 'SUPPLY') NOT NULL DEFAULT 'INGREDIENT';

-- AlterTable
ALTER TABLE `IngredientUnit` ADD COLUMN `category` ENUM('ALL', 'INGREDIENT', 'PACKAGING_MATERIAL', 'SUPPLY') NOT NULL DEFAULT 'ALL';
