import ExcelJS from 'exceljs';
import PDFDocument from 'pdfkit';
import type { TReportColumn, TReportDataset, TReportExportFormat, TReportFilters } from './report.types';

const BRAND_COLOR = 'FF6F4E37';
const HEADER_TEXT_COLOR = 'FFFFFFFF';
const ALT_ROW_COLOR = 'FFF5F0EB';
const SIGNATURE_LABEL = 'Generated By';

const formatFilterSummary = (filters: TReportFilters): string => {
    const parts: string[] = [];

    if (filters.search) parts.push(`Search: ${filters.search}`);
    if (filters.status) parts.push(`Status: ${filters.status}`);
    if (filters.dateFrom) parts.push(`From: ${filters.dateFrom}`);
    if (filters.dateTo) parts.push(`To: ${filters.dateTo}`);
    if (filters.productCategoryId) parts.push(`Category: ${filters.productCategoryId}`);
    if (filters.productTypeId) parts.push(`Type: ${filters.productTypeId}`);
    if (filters.inventoryStatus) parts.push(`Stock Status: ${filters.inventoryStatus}`);
    if (filters.orderStatus) parts.push(`Order Status: ${filters.orderStatus}`);
    if (filters.orderType) parts.push(`Order Type: ${filters.orderType}`);

    return parts.length > 0 ? parts.join(' | ') : 'No filters applied';
};

const getCellValue = (row: Record<string, string | number | null>, column: TReportColumn): string | number => {
    const value = row[column.key];
    if (value === null || value === undefined) return '';
    return value;
};

const formatActorSignatureLine = (dataset: TReportDataset): string => {
    return `${dataset.meta.generatedBy.fullName} - ${dataset.meta.generatedAt}`;
};

export class ReportGenerator {
    async generate(dataset: TReportDataset, format: TReportExportFormat): Promise<{ buffer: Buffer; mimeType: string; extension: string }> {
        if (format === 'excel') {
            return {
                buffer: await this.generateExcel(dataset),
                mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                extension: 'xlsx'
            };
        }

        return {
            buffer: await this.generatePdf(dataset),
            mimeType: 'application/pdf',
            extension: 'pdf'
        };
    }

    private async generateExcel(dataset: TReportDataset): Promise<Buffer> {
        const workbook = new ExcelJS.Workbook();
        workbook.creator = dataset.meta.store.storeName;
        workbook.lastModifiedBy = dataset.meta.generatedBy.fullName;
        workbook.created = new Date();

        const sheet = workbook.addWorksheet('Report', {
            views: [{ state: 'frozen', ySplit: 7 }]
        });

        const columnCount = dataset.columns.length;
        const lastColumnLetter = sheet.getColumn(columnCount).letter;
        const filterSummary = formatFilterSummary(dataset.meta.filters);
        const storeName = dataset.meta.store.storeName.toUpperCase();

        sheet.mergeCells(`A1:${lastColumnLetter}1`);
        sheet.getCell('A1').value = storeName;
        sheet.getCell('A1').font = { bold: true, size: 16, color: { argb: BRAND_COLOR } };
        sheet.getCell('A1').alignment = { horizontal: 'center' };

        sheet.mergeCells(`A2:${lastColumnLetter}2`);
        sheet.getCell('A2').value = dataset.title;
        sheet.getCell('A2').font = { bold: true, size: 13 };
        sheet.getCell('A2').alignment = { horizontal: 'center' };

        sheet.mergeCells(`A3:${lastColumnLetter}3`);
        sheet.getCell('A3').value = dataset.meta.store.address;
        sheet.getCell('A3').font = { size: 10 };
        sheet.getCell('A3').alignment = { horizontal: 'center', wrapText: true };

        sheet.mergeCells(`A4:${lastColumnLetter}4`);
        sheet.getCell('A4').value = `Generated: ${dataset.meta.generatedAt}`;
        sheet.getCell('A4').font = { size: 10, italic: true };
        sheet.getCell('A4').alignment = { horizontal: 'center' };

        sheet.mergeCells(`A5:${lastColumnLetter}5`);
        sheet.getCell('A5').value = filterSummary;
        sheet.getCell('A5').font = { size: 10 };
        sheet.getCell('A5').alignment = { horizontal: 'center', wrapText: true };

        sheet.addRow([]);

        const headerRow = sheet.addRow(dataset.columns.map((column) => column.header));
        const tableHeaderRowNumber = headerRow.number;
        headerRow.height = 22;
        headerRow.eachCell((cell) => {
            cell.font = { bold: true, color: { argb: HEADER_TEXT_COLOR } };
            cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: BRAND_COLOR } };
            cell.alignment = { vertical: 'middle', horizontal: 'center' };
            cell.border = {
                top: { style: 'thin' },
                left: { style: 'thin' },
                bottom: { style: 'thin' },
                right: { style: 'thin' }
            };
        });

        dataset.columns.forEach((column, index) => {
            sheet.getColumn(index + 1).width = column.width ?? 18;
        });

        dataset.rows.forEach((row, rowIndex) => {
            const dataRow = sheet.addRow(dataset.columns.map((column) => getCellValue(row, column)));
            if (rowIndex % 2 === 1) {
                dataRow.eachCell((cell) => {
                    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: ALT_ROW_COLOR } };
                });
            }
            dataRow.eachCell((cell, colNumber) => {
                const column = dataset.columns[colNumber - 1];
                cell.alignment = {
                    vertical: 'middle',
                    horizontal: column?.align ?? 'left',
                    wrapText: true
                };
                cell.border = {
                    top: { style: 'thin', color: { argb: 'FFD9D9D9' } },
                    left: { style: 'thin', color: { argb: 'FFD9D9D9' } },
                    bottom: { style: 'thin', color: { argb: 'FFD9D9D9' } },
                    right: { style: 'thin', color: { argb: 'FFD9D9D9' } }
                };
            });
        });

        this.addExcelSignatureBlock(sheet, dataset, columnCount, lastColumnLetter);

        const summaryRowNumber = (sheet.lastRow?.number ?? tableHeaderRowNumber) + 2;
        sheet.mergeCells(`A${summaryRowNumber}:${lastColumnLetter}${summaryRowNumber}`);
        const summaryCell = sheet.getCell(`A${summaryRowNumber}`);
        summaryCell.value = `Total Records: ${dataset.meta.total}${dataset.meta.truncated ? ' (export truncated to maximum row limit)' : ''}`;
        summaryCell.font = { italic: true, size: 10 };
        summaryCell.alignment = { horizontal: 'left' };

        if (dataset.rows.length > 0) {
            sheet.autoFilter = {
                from: { row: tableHeaderRowNumber, column: 1 },
                to: { row: tableHeaderRowNumber, column: columnCount }
            };
        }

        const buffer = await workbook.xlsx.writeBuffer();
        return Buffer.from(buffer);
    }

    private addExcelSignatureBlock(sheet: ExcelJS.Worksheet, dataset: TReportDataset, columnCount: number, lastColumnLetter: string) {
        const signatureColumnSpan = Math.min(3, columnCount);
        const signatureStartColumn = columnCount - signatureColumnSpan + 1;
        const signatureStartLetter = sheet.getColumn(signatureStartColumn).letter;
        const signatureLine = formatActorSignatureLine(dataset);
        const baseRow = (sheet.lastRow?.number ?? 7) + 2;

        sheet.mergeCells(`${signatureStartLetter}${baseRow}:${lastColumnLetter}${baseRow}`);
        const nameCell = sheet.getCell(`${signatureStartLetter}${baseRow}`);
        nameCell.value = signatureLine;
        nameCell.font = { size: 10 };
        nameCell.alignment = { horizontal: 'center', vertical: 'bottom' };

        const lineRow = baseRow + 1;
        sheet.mergeCells(`${signatureStartLetter}${lineRow}:${lastColumnLetter}${lineRow}`);
        const lineCell = sheet.getCell(`${signatureStartLetter}${lineRow}`);
        lineCell.border = {
            bottom: { style: 'medium', color: { argb: 'FF000000' } }
        };

        const labelRow = baseRow + 2;
        sheet.mergeCells(`${signatureStartLetter}${labelRow}:${lastColumnLetter}${labelRow}`);
        const labelCell = sheet.getCell(`${signatureStartLetter}${labelRow}`);
        labelCell.value = SIGNATURE_LABEL;
        labelCell.font = { size: 9, italic: true, color: { argb: 'FF444444' } };
        labelCell.alignment = { horizontal: 'center', vertical: 'top' };
    }

    private async generatePdf(dataset: TReportDataset): Promise<Buffer> {
        return new Promise((resolve, reject) => {
            const doc = new PDFDocument({
                size: 'A4',
                layout: 'landscape',
                margin: 36,
                bufferPages: true
            });

            const chunks: Buffer[] = [];
            doc.on('data', (chunk: Buffer) => chunks.push(chunk));
            doc.on('end', () => resolve(Buffer.concat(chunks)));
            doc.on('error', reject);

            const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;
            const filterSummary = formatFilterSummary(dataset.meta.filters);
            const storeName = dataset.meta.store.storeName.toUpperCase();

            const drawPageHeader = () => {
                doc.font('Helvetica-Bold').fontSize(16).fillColor('#6F4E37').text(storeName, {
                    align: 'center'
                });
                doc.moveDown(0.2);
                doc.font('Helvetica-Bold').fontSize(12).fillColor('#000000').text(dataset.title, { align: 'center' });
                doc.moveDown(0.2);
                doc.font('Helvetica').fontSize(9).fillColor('#444444').text(dataset.meta.store.address, { align: 'center' });
                doc.moveDown(0.2);
                doc.text(`Generated: ${dataset.meta.generatedAt}`, { align: 'center' });
                doc.text(filterSummary, { align: 'center' });
                doc.moveDown(0.8);
            };

            drawPageHeader();

            const columnWidths = this.calculatePdfColumnWidths(dataset.columns, pageWidth);
            const rowHeight = 22;
            const headerHeight = 26;
            const signatureBlockHeight = 34;
            const summaryLineHeight = 14;
            const footerBlockHeight = signatureBlockHeight + summaryLineHeight + 16;
            let y = doc.y;

            const drawTableHeader = () => {
                let x = doc.page.margins.left;
                doc.font('Helvetica-Bold').fontSize(8).fillColor('#FFFFFF');

                dataset.columns.forEach((column, index) => {
                    const width = columnWidths[index];
                    doc.save();
                    doc.rect(x, y, width, headerHeight).fill('#6F4E37');
                    doc.fillColor('#FFFFFF').text(column.header, x + 4, y + 7, {
                        width: width - 8,
                        align: column.align ?? 'left',
                        lineBreak: false
                    });
                    doc.restore();
                    x += width;
                });

                y += headerHeight;
            };

            const ensureSpace = (requiredHeight: number) => {
                const bottom = doc.page.height - doc.page.margins.bottom;
                if (y + requiredHeight > bottom) {
                    doc.addPage();
                    y = doc.page.margins.top;
                    drawPageHeader();
                    drawTableHeader();
                }
            };

            drawTableHeader();

            dataset.rows.forEach((row, rowIndex) => {
                ensureSpace(rowHeight);

                let x = doc.page.margins.left;
                const fillColor = rowIndex % 2 === 1 ? '#F5F0EB' : '#FFFFFF';

                dataset.columns.forEach((column, index) => {
                    const width = columnWidths[index];
                    doc.save();
                    doc.rect(x, y, width, rowHeight).fill(fillColor);
                    doc.fillColor('#000000')
                        .font('Helvetica')
                        .fontSize(7.5)
                        .text(String(getCellValue(row, column)), x + 4, y + 6, {
                            width: width - 8,
                            align: column.align ?? 'left',
                            lineBreak: false
                        });
                    doc.restore();
                    x += width;
                });

                y += rowHeight;
            });

            ensureSpace(footerBlockHeight);
            const signatureY = y + 12;
            this.drawPdfSignatureBlock(doc, dataset, pageWidth, signatureY);

            const pages = doc.bufferedPageRange();
            const summaryY = signatureY + signatureBlockHeight;
            doc.font('Helvetica').fontSize(8).fillColor('#666666');
            doc.text(
                `Page ${pages.count} of ${pages.count} | Total Records: ${dataset.meta.total}${dataset.meta.truncated ? ' (truncated)' : ''}`,
                doc.page.margins.left,
                summaryY,
                { align: 'left', width: pageWidth }
            );

            doc.end();
        });
    }

    private drawPdfSignatureBlock(doc: InstanceType<typeof PDFDocument>, dataset: TReportDataset, pageWidth: number, startY: number) {
        const signatureWidth = Math.min(pageWidth * 0.34, 220);
        const signatureX = doc.page.margins.left + pageWidth - signatureWidth;
        const signatureLine = formatActorSignatureLine(dataset);

        doc.font('Helvetica').fontSize(9).fillColor('#000000').text(signatureLine, signatureX, startY, {
            width: signatureWidth,
            align: 'center'
        });

        const lineY = startY + 16;
        doc.moveTo(signatureX, lineY)
            .lineTo(signatureX + signatureWidth, lineY)
            .lineWidth(1)
            .strokeColor('#000000')
            .stroke();

        doc.font('Helvetica')
            .fontSize(8)
            .fillColor('#444444')
            .text(SIGNATURE_LABEL, signatureX, lineY + 6, {
                width: signatureWidth,
                align: 'center'
            });
    }

    private calculatePdfColumnWidths(columns: TReportColumn[], totalWidth: number): number[] {
        const totalWeight = columns.reduce((sum, column) => sum + (column.width ?? 18), 0);
        return columns.map((column) => ((column.width ?? 18) / totalWeight) * totalWidth);
    }
}
